### ISSUE TITLE
检查一下泉州网，返回信息为版权与免责声明:

### ISSUE THREAD

**Issue by xmd2003** [SagittariusZhu/wxmblog#6]
泉州网新闻返回信息全部为：
泉州网版权与免责声明:

① 未经本网授权不得转载、摘编或利用其它方式使用本网原创作品。已经本网授权使用作品的，应在授权范围内使用，并注明“来源：泉州网”。违反上述声明者，本网将追究其相关法律责任。泉州网欢迎各兄弟网站开展平等合作。

② 凡本网注明“来源：XXX（非泉州网）”的作品，均转载自其他媒体，转载目的在于传递更多信息，并不代表泉州网赞同其观点和对其真实性负责，被转载网站、媒体、当事人若认为有侵权之处请来电告知，我们将及时处理。

③ 如因作品内容、版权和其他问题需要同泉州网联系的，请致电0595-22500194，或E-mail至：web@qzwb.com

**Comment by SagittariusZhu** [comment]
是自动抽取代码有问题，已修复。
