### ISSUE TITLE
频道增加查看数据来源（原来有这个功能）

### ISSUE THREAD

**Issue by xmd2003** [SagittariusZhu/wxmblog#8]
增加根据频道查看数据来源的功能，并按照多少来排序，如果有一个占比更好。譬如信息来自5个数据源，一共100条，而数据源a占30条，占比则为30%

**Comment by SagittariusZhu** [comment]
在查看频道信息中增加了数据源统计信息

![image](https://user-images.githubusercontent.com/24883892/27421662-fe19c3ea-575d-11e7-890a-00dd36456009.png)

点击查看详情可以看到更具体的统计数据。
